In [ ]:
#https://tinyurl.com/3dt4mbs6
#Preiction for, to lbuy a car or not
# Random Forest Classification, decission tree classiification

: 

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd



In [3]:
df = pd.read_csv("car_data.csv")

In [4]:
display(df.head(5))

User ID Gender  Age  AnnualSalary  Purchased
0      385   Male   35         20000          0
1      681   Male   40         43500          0
2      353   Male   49         74000          0
3      895   Male   40        107500          1
4      661   Male   25         79000          0

In [5]:
X = df.iloc[:400,[2,3]].values
y = df.iloc[:400,-1].values
print(X)

[[    35  20000]
 [    40  43500]
 [    49  74000]
 [    40 107500]
 [    25  79000]
 [    47  33500]
 [    46 132500]
 [    42  64000]
 [    30  84500]
 [    41  52000]
 [    42  80000]
 [    47  23000]
 [    32  72500]
 [    27  57000]
 [    42 108000]
 [    33 149000]
 [    35  75000]
 [    35  53000]
 [    46  79000]
 [    39 134000]
 [    39  51500]
 [    49  39000]
 [    54  25500]
 [    41  61500]
 [    31 117500]
 [    24  58000]
 [    40 107000]
 [    40  97500]
 [    48  29000]
 [    38 147500]
 [    45  26000]
 [    32  67500]
 [    37  62000]
 [    41  79500]
 [    44 113500]
 [    47  41500]
 [    38  55000]
 [    39 114500]
 [    42  73000]
 [    26  15000]
 [    21  37500]
 [    59  39500]
 [    39  66500]
 [    43  80500]
 [    49  86000]
 [    37  75000]
 [    49  76500]
 [    28 123000]
 [    59  48500]
 [    40  60500]
 [    38  99500]
 [    51  35500]
 [    55 130000]
 [    23  56500]
 [    49  43500]
 [    49  36000]
 [    48  21500]
 [    49  98500]
 [    43  5950

In [6]:
sampled_df = df.sample(n=400) # selecting the random 400 rows
X = sampled_df.iloc[:,[2,3]].values
y = sampled_df.iloc[:,-1].values
print(X)

[[    28  58500]
 [    49  81500]
 [    41  61500]
 [    49  91500]
 [    60  83000]
 [    31 118000]
 [    28  79000]
 [    39  62500]
 [    25  33500]
 [    29  33500]
 [    46 114500]
 [    40  59500]
 [    45  67500]
 [    24  58000]
 [    34 114500]
 [    52  21000]
 [    25  20500]
 [    56 104000]
 [    36  76500]
 [    28  32500]
 [    42  75500]
 [    23  28500]
 [    37 126500]
 [    41  59000]
 [    25  90500]
 [    31  71000]
 [    28  59000]
 [    31  81500]
 [    33 101500]
 [    36 109500]
 [    47 141500]
 [    53 143000]
 [    38  53500]
 [    55 116500]
 [    59  62500]
 [    29  83000]
 [    47  49000]
 [    39  96000]
 [    38  59500]
 [    52  90500]
 [    46 131500]
 [    61  43500]
 [    47  50000]
 [    45  55500]
 [    36  73500]
 [    49  97500]
 [    49 141000]
 [    35  59000]
 [    42  73500]
 [    37  62000]
 [    52  38000]
 [    39 120500]
 [    39  75000]
 [    56 131500]
 [    35  44500]
 [    35  65000]
 [    38  80500]
 [    31  90500]
 [    40  8150

In [7]:
#splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [15]:
#feature scaling
#Import the necessary libraries:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

#create a logistic regression classifier
classifier = LogisticRegression()

In [16]:
#create a standardscaler object and fit it to the training data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

# scale the feature in the test set(X_train):
X_test = sc.transform(X_test)

# if y_train is a 2D array, you need to flatten it to a 1D array using ravel() function:
y_train = y_train.ravel()

#Fit the logistic regression model using the scaled training data:
classifier.fit(X_train, y_train)
print(X_train)

[[-1.19950928e+00  4.33678080e-01]
 [-8.28527030e-01  1.25535460e+00]
 [-4.57544778e-01  2.07703111e+00]
 [-2.72053652e-01 -6.76838622e-02]
 [ 4.69910853e-01  1.63137605e+00]
 [ 4.69910853e-01  1.89598375e+00]
 [-1.66323710e+00 -1.52998953e+00]
 [ 6.55401979e-01 -1.37679560e+00]
 [-1.79308089e-01 -3.18364833e-01]
 [ 3.77165290e-01 -4.99412202e-01]
 [-3.64799215e-01  1.99347079e+00]
 [ 6.18303754e-03 -7.08313011e-01]
 [-6.43035904e-01  2.13273800e+00]
 [-1.57049153e+00 -1.22360167e+00]
 [-8.28527030e-01 -1.51606281e+00]
 [ 6.55401979e-01  1.99347079e+00]
 [ 1.91674164e-01  2.98031821e-02]
 [-2.72053652e-01 -2.90511392e-01]
 [-7.35781467e-01  3.77971198e-01]
 [-2.03421935e+00 -1.23390745e-01]
 [-1.79308089e-01 -2.76584672e-01]
 [-3.64799215e-01 -2.62657951e-01]
 [-2.72053652e-01 -2.20877789e-01]
 [-2.72053652e-01 -5.82972525e-01]
 [ 1.91674164e-01  1.94974089e-03]
 [ 9.89286006e-02 -1.19769797e-02]
 [-2.72053652e-01  1.50603557e+00]
 [-1.19950928e+00 -1.50213609e+00]
 [ 2.84419727e-01  2

In [17]:
print(y_train)
# 0 means not buy, 1 means buy
# 1D array


[0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 0
 0 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1
 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 1 1 1 1
 1 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1
 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0
 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 1 0 1 1 0 0 0 1 1 0
 1 1 0 1]
